//
//  NewsDetailPresenter.swift
//  NewsAppAlTayer
//
//  Created by Fazeel Ahmed on 7/10/20.
//  Copyright (c) 2020 Sun and Sand Sports LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsDetailPresentationLogic
{
    func presentArticle(response: NewsDetail.Something.Response)
}

class NewsDetailPresenter: NewsDetailPresentationLogic
{
    
    weak var viewController: NewsDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentArticle(response: NewsDetail.Something.Response)
    {
        //
    }
}
