//
//  NewsWorker.swift
//  NewsAppAlTayer
//
//  Created by Fazeel Ahmed on 7/9/20.
//  Copyright (c) 2020 Sun and Sand Sports LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsEntityGatewayProtocol {
    func fetchNewsArticles(request : News.Articles.Request, completion: @escaping (Result<Articles_Base?, APIError>) -> Void)
}

class NewsWorker : APIClient , NewsEntityGatewayProtocol
{
    var session: URLSession
    
    init(configuration: URLSessionConfiguration) {
        self.session = URLSession(configuration: configuration)
    }
    
    convenience init() {
        self.init(configuration: .default)
    }
    
    
  func fetchNewsArticles(request : News.Articles.Request, completion: @escaping (Result<Articles_Base?, APIError>) -> Void) {
    
     if let request = NewsApiTarget.getArticles(request: request).urlRequest {
          fetch(with: request, decode: { json -> Articles_Base? in
              guard let result = json as? Articles_Base else { return  nil }
              return result
          }, completion: completion)
      }
    
  }
}
