//
//  NewsPresenter.swift
//  NewsAppAlTayer
//
//  Created by Fazeel Ahmed on 7/9/20.
//  Copyright (c) 2020 Sun and Sand Sports LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewsPresentationLogic
{
  func getArticles(response: News.Articles.Response)
}

class NewsPresenter: NewsPresentationLogic
{
  weak var viewController: NewsDisplayLogic?
  
  // MARK: Do something
  
  func getArticles(response: News.Articles.Response)
  {
    
    var displayArticles : [News.Articles.ViewModel.DisplayedDocs] = []
    
    if let response = response.response {
        if let doc = response.response?.docs {
            
            for docs in doc {
                let displayArticle = News.Articles.ViewModel.DisplayedDocs(lead_paragraph: docs.lead_paragraph, abstract: docs.abstract, headline: docs.headline , snippet: docs.snippet ,pub_date: docs.pub_date , multimedia: docs.multimedia , web_url: docs.web_url)
                displayArticles.append(displayArticle)
            }
        
        }
    }
    
    let viewmodel = News.Articles.ViewModel(displayedArticles: displayArticles , error: response.error)
    viewController?.displayArticles(viewModel: viewmodel)
  }
}
