//
//  NewsRouter.swift
//  NewsAppAlTayer
//
//  Created by Fazeel Ahmed on 7/9/20.
//  Copyright (c) 2020 Sun and Sand Sports LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewsRoutingLogic
{
    func routeToDetails(segue: UIStoryboardSegue?)
}

protocol NewsDataPassing
{
    var dataStore: NewsDataStore? { get set}
}

class NewsRouter: NSObject, NewsRoutingLogic, NewsDataPassing
{
    weak var viewController: NewsViewController?
    var dataStore: NewsDataStore?
    
    // MARK: Routing
    
    func routeToDetails(segue: UIStoryboardSegue?)
    {
        if let _ = segue {
            //
        } else {
            let destinationVC = Storyboard.newDetailsController.viewController as! NewsDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToDetails(source: dataStore!, destination: &destinationDS)
            navigateToDetails(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToDetails(source: NewsViewController, destination: NewsDetailViewController)
    {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetails(source: NewsDataStore, destination: inout NewsDetailDataStore)
    {
        destination.article = source.article
    }
}
