//
//  NewsModels.swift
//  NewsAppAlTayer
//
//  Created by Fazeel Ahmed on 7/9/20.
//  Copyright (c) 2020 Sun and Sand Sports LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum News
{
    // MARK: Use cases
    
    enum Articles
    {
        struct Request
        {
            var apikey : String = Environment().apiKey
            var query : String = ""
            var page : Int = 0
            var freshRequest : Bool =  false
        }
        struct Response
        {
            var response : Articles_Base? = nil
            var error : String? = nil
        }
        
        struct ViewModel
        {
            struct DisplayedDocs
            {
                var lead_paragraph: String?
                var abstract: String?
                var headline : Headline?
                var snippet : String?
                var pub_date : String?
                var multimedia : [Multimedia]?
                var web_url : String?
            }
            var displayedArticles: [DisplayedDocs]
            var error : String? = nil
        }
    }
    
}
